{
 "title": "My Room Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dt AS \"time\", (temperature_bme + temperature_sht) / 2.0 AS \"value\" FROM room_mine ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dt AS \"time\", (humidity_bme + humidity_sht) / 2.0 AS \"value\" FROM room_mine ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dt as \"time\", co2 as \"value\" FROM room_mine ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dt AS \"time\", (temperature_bme + temperature_sht) / 2.0 AS \"value\" FROM outside ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dt AS \"time\", (humidity_bme + humidity_sht) / 2.0 AS \"value\" FROM outside ORDER BY dt DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT dt as \"time\", temperature_bme\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    },
    {
     "rawSql": "SELECT dt as \"time\", temperature_sht\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT dt as \"time\", humidity_bme\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    },
    {
     "rawSql": "SELECT dt as \"time\", humidity_sht\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ppt" } },
   "targets": [
    {
     "rawSql": "SELECT dt as \"time\", co2\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    }
   ]
  },
  {
   "title": "Particulates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µg/m3" } },
   "targets": [
    {
     "rawSql": "SELECT dt as \"time\", pm01 as \"PM 0.1\"\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    },
    {
     "rawSql": "SELECT dt as \"time\", pm25 as \"PM 2.5\"\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    },
    {
     "rawSql": "SELECT dt as \"time\", pm10 as \"PM 10\"\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mm Hg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  dt AS \"time\",\n  pressure_bme AS \"value\"\nFROM room_mine\nWHERE $__timeFilter(dt)\nORDER BY dt ASC"
    }
   ]
  }
 ]
}